buildscript {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.minecraftforge.net/' }
    }
    dependencies {
        classpath('com.anatawa12.forge:ForgeGradle:1.2-1.1.+') {
            changing = true
        }
    }
}

apply plugin: 'forge'

if (JavaVersion.current() != JavaVersion.VERSION_1_8) {
    throw new GradleException('Lootable Bodies Reanimated requires Java 8.')
}

def versionProperties = new Properties()
file('version.properties').withInputStream { versionProperties.load(it) }

version = versionProperties.getProperty('mod_version')
group = 'cyano.lootable'
archivesBaseName = 'LootableBodiesReanimated'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

minecraft {
    version = '1.7.10-10.13.4.1614-1.7.10'
    runDir = 'run'
    replace '@MOD_VERSION@', project.version
    replaceIn 'cyano/lootable/LootableBodies.java'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', '1.7.10'
    filesMatching('mcmod.info') {
        expand version: project.version, mcversion: '1.7.10'
    }
}
